---
- name: Start gluetun
  block:
    - name: Gather info about child containers
      community.docker.docker_container_info:
        name: "{{ item.name }}"
      loop: "{{ gluetun_routed_containers }}"
      register: child_container_info

    - name: Determine which containers are actually running
      ansible.builtin.set_fact:
        running_routed_containers: >-
          {{
            child_container_info.results
            | selectattr('container', 'defined')
            | selectattr('container.State.Status', '==', 'running')
            | map(attribute='item')
            | list
          }}

    - name: Stop the currently running child containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: stopped
      loop: "{{ running_routed_containers }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Stop gluetun
      community.docker.docker_container:
        name: "{{ gluetun_container_name }}"
        state: stopped

    - name: Remove Gluetun auth directory
      ansible.builtin.file:
        path: "{{ gluetun_config_directory }}/auth"
        state: absent

    - name: Create Gluetun config directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: 1000
        group: 1000
      loop:
        - "{{ gluetun_config_directory }}/wireguard"
        - "{{ gluetun_config_directory }}/auth"

    - name: Create minimal Gluetun auth config file for future compatibility
      ansible.builtin.copy:
        dest: "{{ gluetun_config_directory }}/auth/config.toml"
        content: |
          [[roles]]
          name = "default"
          routes = [
            "GET /v1/dns/status",
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/status",
            "GET /v1/updater/status"
          ]
          auth = "none"
        owner: 1000
        group: 1000
        mode: '0644'

    - name: Flatten child container ports
      ansible.builtin.set_fact:
        gluetun_combined_ports: >-
          {{
            [ gluetun_http_port ]
            + (gluetun_routed_containers | map(attribute='ports') | list | flatten)
          }}

    - name: Create/Start Gluetun container
      community.docker.docker_container:
        name: "{{ gluetun_container_name }}"
        image: "{{ gluetun_image_name }}:{{ gluetun_image_version }}"
        pull: true
        capabilities:
          - NET_ADMIN
        volumes:
          - "{{ gluetun_config_directory }}/wireguard:/gluetun/wireguard/:rw"
          - "/etc/resolv.conf:/etc/resolv.conf:rw"
          - "{{ gluetun_config_directory }}/auth/config.toml:/gluetun/auth/config.toml:ro"
        ports: "{{ gluetun_combined_ports }}"
        env:
          VPN_SERVICE_PROVIDER: "custom"
          VPN_TYPE: "wireguard"
          DNS_UPDATE_PERIOD: "30m"
          VPN_INTERFACE: "wg0"
          VPN_OUTPUT_INTERFACE: "eth0"
          BLOCK_MALICIOUS: "off"
          CONTROL_SERVER_LOGGING: "on"
          HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: "/gluetun/auth/config.toml"
        restart_policy: unless-stopped
        image_name_mismatch: recreate
        memory: "{{ gluetun_memory }}"
        labels:
          traefik.enable: "{{ gluetun_available_externally | string }}"
          traefik.http.routers.gluetun.rule: "Host(`{{ gluetun_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.gluetun.tls.certresolver: "letsencrypt"
          traefik.http.routers.gluetun.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.gluetun.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.gluetun.loadbalancer.server.port: "8000"
        healthcheck:
          test: ["CMD", "wget", "-qO-", "http://localhost:8000/v1/dns/status"]
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 30s

    - name: Wait for Gluetun container to be healthy
      community.docker.docker_container_info:
        name: "{{ gluetun_container_name }}"
      register: gluetun_status
      until: gluetun_status.container.State.Health.Status == "healthy"
      retries: 30
      delay: 5
      changed_when: false

  when: gluetun_enabled is true


- name: Stop gluetun
  block:
    - name: Stop gluetun
      community.docker.docker_container:
        name: "{{ gluetun_container_name }}"
        state: absent
  when: gluetun_enabled is false