---
vpn_download_stack_enabled: false

# The stack enables the common download apps that should share Gluetun's network
# namespace. Apps can still be disabled individually after the stack role runs.
vpn_download_stack_prowlarr_enabled: true
vpn_download_stack_deluge_enabled: true
vpn_download_stack_radarr_enabled: true
vpn_download_stack_sonarr_enabled: true
vpn_download_stack_nzbget_enabled: true
vpn_download_stack_readarr_enabled: false
vpn_download_stack_jackett_enabled: false
vpn_download_stack_sabnzbd_enabled: false
