---
- name: Start Radarr
  block:
    - name: Create Radarr config directory
      ansible.builtin.file:
        path: "{{ radarr_data_directory }}"
        state: directory
        owner: "{{ radarr_user_id }}"
        group: "{{ radarr_group_id }}"
        mode: "0775"
        recurse: true

    - name: Create Radarr media directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ radarr_user_id }}"
        group: "{{ radarr_group_id }}"
        mode: "0775"
      with_items:
        - "{{ radarr_movies_directory }}"
        - "{{ radarr_download_directory }}"

    - name: Radarr Docker Container
      community.docker.docker_container:
        name: "{{ radarr_container_name }}"
        image: "{{ radarr_image_name }}:{{ radarr_image_version }}"
        pull: true
        volumes:
          - "{{ radarr_movies_directory }}:/movies:rw"
          - "{{ radarr_download_directory }}:/downloads:rw"
          - "{{ radarr_data_directory }}:/config:rw"
        ports: "{{ [radarr_port ~ ':7878'] if not (vpn_download_stack_enabled | default(false) | bool) else omit }}"
        network_mode: "{{ gluetun_name if (vpn_download_stack_enabled | default(false) | bool) else omit }}"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ radarr_user_id }}"
          PGID: "{{ radarr_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ radarr_memory }}"
        labels:
          traefik.enable: "{{ radarr_available_externally | string }}"
          traefik.http.routers.radarr.rule: "Host(`{{ radarr_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.radarr.tls.certresolver: "letsencrypt"
          traefik.http.routers.radarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.radarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.radarr.loadbalancer.server.port: "7878"
          homepage.group: "Download Tools"
          homepage.name: "Radarr"
          homepage.icon: "radarr"
          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ radarr_port }}"

      register: docker_container_result
      until: docker_container_result is succeeded
      retries: "{{ docker_container_pull_retries }}"
      delay: "{{ docker_container_pull_delay }}"
  when: radarr_enabled is true
- name: Stop Radarr
  block:
    - name: Stop Radarr
      community.docker.docker_container:
        name: "{{ radarr_container_name }}"
        state: absent
  when: radarr_enabled is false
