---
- name: Restart Grafana
  community.docker.docker_container:
    name: "{{ stats_grafana_container_name }}"
    image: "{{ stats_grafana_image_name }}:{{ stats_grafana_image_version }}"
    state: started
    restart: true
  listen: "restart grafana"
